### ISSUE TITLE
images not loading

### ISSUE THREAD

**Issue by rossjami** [sfu-dhil/material-culture#42]
**Describe the bug**
Browsing by images shows broken image symbol

**To Reproduce**
1. Go to https://dhil.lib.sfu.ca/material-culture/image/
2. See error - image link broken

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ubermichael** [comment]
So this one took a long time to fix. I think it's a bug in the paginator library I've been using, but to figure that out might take a few days. For now, it's better.
