### ISSUE TITLE
Announcement Post Creation Error

### ISSUE THREAD

**Issue by alexxanthoudakis** [sfu-dhil/material-culture#50]
**Describe the bug**
When you attempt to create an announcement post on the Material Cultures website, you get a 500 Internal Server Error.

**To Reproduce**
1. Go to All Announcements
2. Click New
3. Make a post and click Create

**Expected behavior**
I expected to be able to create a post

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome

**Comment by ubermichael** [comment]
This was a permissions error which has been fixed.
