### ISSUE TITLE
Bottles Search Error

### ISSUE THREAD

**Issue by alexxanthoudakis** [sfu-dhil/material-culture#51]
**Describe the bug**
When you attempt to search the Bottles page on the Material Cultures website, you get a 500 Internal Server Error.

**To Reproduce**
1. Go to Bottles in the Explore dropdown
2. Click on Search

**Expected behavior**
To be able to search the bottles

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome

**Comment by ubermichael** [comment]
Closing, as this seems like an archivable project.
