### ISSUE TITLE
Can Search Error

### ISSUE THREAD

**Issue by alexxanthoudakis** [sfu-dhil/material-culture#52]
**Describe the bug**
When searching the Material Cultures Can List, you get 500 Internal Server Error.

**To Reproduce**
1. Go to Cans under the Explore dropdown
2. Click on Search
3. See error

**Expected behavior**
I expected to be able to search the list.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome

**Comment by ubermichael** [comment]
Closing, as this seems like an archivable project.
