### ISSUE TITLE
Creation of New Ceramic Vessel Error

### ISSUE THREAD

**Issue by alexxanthoudakis** [sfu-dhil/material-culture#62]
**Describe the bug**
When trying to create a new Vessel on the Material Cultures Ceramic Vessels page, you get a 500 Internal Server Error.

**To Reproduce**
1. Go to Ceramic Vessels under the Explore dropdown
2. Click on Search
3. See error

**Expected behavior**
I expected to be able to create a new record

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome

**Comment by ubermichael** [comment]
The steps say search, but the description says create a new vessel. Can you please clarify the issue. :)

**Comment by alexxanthoudakis** [comment]
Sorry Michael, I was in copy/paste mode! It's to create a new vessel--I totally forgot to go through the steps:

1. Go to Ceramic Vessels under the Explore dropdown
2. Click on New
3. See error
