### ISSUE TITLE
Comments Page Error

### ISSUE THREAD

**Issue by alexxanthoudakis** [sfu-dhil/material-culture#63]
**Describe the bug**
Can't look at the Comments page for Material Cultures; you get a 403 forbidden error.

**To Reproduce**
1. Go to Comments on the Feedback dropdown
2. Click on Comments
3. See error

**Expected behavior**
To see the comments page.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome

**Comment by ubermichael** [comment]
This was a permissions error. Fixed now!
