### ISSUE TITLE
Comment Notes Page Error

### ISSUE THREAD

**Issue by alexxanthoudakis** [sfu-dhil/material-culture#64]
**Describe the bug**
Can't look at the Comment Notes page for Material Cultures; you get a 403 forbidden error.

**To Reproduce**
1. Go to Comment Notes on the Feedback dropdown
2. See error

**Expected behavior**
To see the comment notes page.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome

**Comment by ubermichael** [comment]
This was a permissions error. Fixed now!
